
const SUBJECTS = {
  primero:[
    {id:'montaje',name:'Montaje y mantenimiento',icon:'&#128295;',desc:'Componentes hardware, ensamblaje y diagnostico',color:'#00f2ff'},
    {id:'sistemas',name:'Sistemas operativos monopuesto',icon:'&#128187;',desc:'Instalacion y administracion de SO',color:'#7000ff'},
    {id:'ofimatica',name:'Aplicaciones ofimaticas',icon:'&#128202;',desc:'Herramientas de oficina y productividad',color:'#00ff9d'},
    {id:'redes',name:'Redes locales',icon:'&#127760;',desc:'Fundamentos de redes y conectividad',color:'#ff0055'},
    {id:'empleabilidad',name:'Empleabilidad I',icon:'&#128084;',desc:'Desarrollo profesional y busqueda de empleo',color:'#9d4edd'}
  ],
  segundo:[
    {id:'sistemasred',name:'Sistemas operativos en red',icon:'&#128421;',desc:'Servidores y administracion de red',color:'#00f2ff'},
    {id:'seguridad',name:'Seguridad informatica',icon:'&#128274;',desc:'Proteccion de sistemas y datos',color:'#7000ff'},
    {id:'servicios',name:'Servicios en red',icon:'&#9881;',desc:'Configuracion de servicios de red',color:'#00ff9d'},
    {id:'web',name:'Aplicaciones web',icon:'&#127757;',desc:'Desarrollo y despliegue web',color:'#ff0055'},
    {id:'ingles',name:'Ingles Profesional',icon:'&#127468;&#127463;',desc:'Vocabulario tecnico en ingles',color:'#ffcc00'},
    {id:'empleabilidad2',name:'Empleabilidad II',icon:'&#128104;&#8205;&#128188;',desc:'Gestion avanzada de carrera profesional',color:'#ffcc00'},
    {id:'proyecto',name:'Proyecto intermodular',icon:'&#128203;',desc:'Gestion y desarrollo de proyectos',color:'#9d4edd'}
  ]
};

const LEVELS = {
  montaje_facil:{icon:'&#128295;',title:'Facil',desc:'Componentes basicos',cost:0,color:'#10b981',year:'primero',subj:'Montaje'},
  montaje_medio:{icon:'&#128295;',title:'Medio',desc:'Ensamblaje y diagnostico',cost:150,color:'#f59e0b',year:'primero',subj:'Montaje'},
  montaje_dificil:{icon:'&#128295;',title:'Dificil',desc:'Config. avanzada',cost:350,color:'#ef4444',year:'primero',subj:'Montaje'},
  sistemas_facil:{icon:'&#128187;',title:'Facil',desc:'SO basicos',cost:0,color:'#10b981',year:'primero',subj:'Sistemas'},
  sistemas_medio:{icon:'&#128187;',title:'Medio',desc:'Administracion de SO',cost:150,color:'#f59e0b',year:'primero',subj:'Sistemas'},
  sistemas_dificil:{icon:'&#128187;',title:'Dificil',desc:'Config. avanzada',cost:350,color:'#ef4444',year:'primero',subj:'Sistemas'},
  ofimatica_facil:{icon:'&#128202;',title:'Facil',desc:'Herramientas basicas',cost:0,color:'#10b981',year:'primero',subj:'Ofimatica'},
  ofimatica_medio:{icon:'&#128202;',title:'Medio',desc:'Funciones avanzadas',cost:150,color:'#f59e0b',year:'primero',subj:'Ofimatica'},
  ofimatica_dificil:{icon:'&#128202;',title:'Dificil',desc:'Macros y automatizacion',cost:350,color:'#ef4444',year:'primero',subj:'Ofimatica'},
  redes_facil:{icon:'&#127760;',title:'Facil',desc:'Conceptos de redes',cost:0,color:'#10b981',year:'primero',subj:'Redes'},
  redes_medio:{icon:'&#127760;',title:'Medio',desc:'Protocolos y config.',cost:150,color:'#f59e0b',year:'primero',subj:'Redes'},
  redes_dificil:{icon:'&#127760;',title:'Dificil',desc:'Config. avanzada',cost:350,color:'#ef4444',year:'primero',subj:'Redes'},
  empleabilidad_facil:{icon:'&#128084;',title:'Facil',desc:'Busqueda de empleo',cost:0,color:'#10b981',year:'primero',subj:'Empleabilidad I'},
  empleabilidad_medio:{icon:'&#128084;',title:'Medio',desc:'Desarrollo profesional',cost:150,color:'#f59e0b',year:'primero',subj:'Empleabilidad I'},
  empleabilidad_dificil:{icon:'&#128084;',title:'Dificil',desc:'Gestion de carrera',cost:350,color:'#ef4444',year:'primero',subj:'Empleabilidad I'},
  sistemasred_facil:{icon:'&#128421;',title:'Facil',desc:'Servidores basicos',cost:0,color:'#10b981',year:'segundo',subj:'Sistemas en Red'},
  sistemasred_medio:{icon:'&#128421;',title:'Medio',desc:'Admin. servidores',cost:200,color:'#f59e0b',year:'segundo',subj:'Sistemas en Red'},
  sistemasred_dificil:{icon:'&#128421;',title:'Dificil',desc:'Config. avanzada',cost:450,color:'#ef4444',year:'segundo',subj:'Sistemas en Red'},
  seguridad_facil:{icon:'&#128274;',title:'Facil',desc:'Conceptos basicos',cost:0,color:'#10b981',year:'segundo',subj:'Seguridad'},
  seguridad_medio:{icon:'&#128274;',title:'Medio',desc:'Herramientas de seguridad',cost:200,color:'#f59e0b',year:'segundo',subj:'Seguridad'},
  seguridad_dificil:{icon:'&#128274;',title:'Dificil',desc:'Auditoria y hacking etico',cost:450,color:'#ef4444',year:'segundo',subj:'Seguridad'},
  servicios_facil:{icon:'&#9881;',title:'Facil',desc:'Servicios basicos',cost:0,color:'#10b981',year:'segundo',subj:'Servicios'},
  servicios_medio:{icon:'&#9881;',title:'Medio',desc:'Config. de servicios',cost:200,color:'#f59e0b',year:'segundo',subj:'Servicios'},
  servicios_dificil:{icon:'&#9881;',title:'Dificil',desc:'Servicios avanzados',cost:450,color:'#ef4444',year:'segundo',subj:'Servicios'},
  web_facil:{icon:'&#127757;',title:'Facil',desc:'Desarrollo web basico',cost:0,color:'#10b981',year:'segundo',subj:'Web'},
  web_medio:{icon:'&#127757;',title:'Medio',desc:'Frameworks y BBDD',cost:200,color:'#f59e0b',year:'segundo',subj:'Web'},
  web_dificil:{icon:'&#127757;',title:'Dificil',desc:'Desarrollo avanzado',cost:450,color:'#ef4444',year:'segundo',subj:'Web'},
  ingles_facil:{icon:'&#127468;&#127463;',title:'Facil',desc:'Vocabulario basico',cost:0,color:'#10b981',year:'segundo',subj:'Ingles'},
  ingles_medio:{icon:'&#127468;&#127463;',title:'Medio',desc:'Terminos tecnicos',cost:200,color:'#f59e0b',year:'segundo',subj:'Ingles'},
  ingles_dificil:{icon:'&#127468;&#127463;',title:'Dificil',desc:'Vocabulario avanzado',cost:450,color:'#ef4444',year:'segundo',subj:'Ingles'},
  empleabilidad2_facil:{icon:'&#128104;&#8205;&#128188;',title:'Facil',desc:'Derechos laborales',cost:0,color:'#10b981',year:'segundo',subj:'Empleabilidad II'},
  empleabilidad2_medio:{icon:'&#128104;&#8205;&#128188;',title:'Medio',desc:'Contratos y nominas',cost:200,color:'#f59e0b',year:'segundo',subj:'Empleabilidad II'},
  empleabilidad2_dificil:{icon:'&#128104;&#8205;&#128188;',title:'Dificil',desc:'Liderazgo y emprendimiento',cost:450,color:'#ef4444',year:'segundo',subj:'Empleabilidad II'},
  proyecto_facil:{icon:'&#128203;',title:'Facil',desc:'Gestion basica',cost:0,color:'#10b981',year:'segundo',subj:'Proyecto'},
  proyecto_medio:{icon:'&#128203;',title:'Medio',desc:'Metodologias agiles',cost:200,color:'#f59e0b',year:'segundo',subj:'Proyecto'},
  proyecto_dificil:{icon:'&#128203;',title:'Dificil',desc:'Gestion avanzada',cost:450,color:'#ef4444',year:'segundo',subj:'Proyecto'}
};

const QS = {
  montaje_facil:[{q:'Que componente es el cerebro del ordenador?',a:['cpu','procesador'],pts:10},{q:'Que tipo de memoria es volatil?',a:['ram','memoria ram'],pts:10},{q:'Que significa BIOS?',a:['basic input output system'],pts:10},{q:'Que dispositivo almacena datos permanentemente?',a:['disco duro','hdd'],pts:10},{q:'Que componente convierte corriente alterna a continua?',a:['fuente de alimentacion'],pts:10},{q:'Que ranura es para tarjetas graficas?',a:['pci express','pcie'],pts:10},{q:'Que herramienta evita descargas electrostaticas?',a:['pulsera antiestatica'],pts:10},{q:'Que pasta se aplica entre CPU y disipador?',a:['pasta termica'],pts:10},{q:'Que conector usa monitores digitales HD?',a:['hdmi','displayport'],pts:10},{q:'Que indica un pitido largo al encender el PC?',a:['error de memoria'],pts:10}],
  montaje_medio:[{q:'Cuantos pines tiene un conector ATX moderno?',a:['24','24 pines'],pts:15},{q:'Que formato de particion soporta discos mayores de 2TB?',a:['gpt'],pts:15},{q:'Que herramienta crimpa cables de red?',a:['crimpadora'],pts:15},{q:'Que programa comprueba la memoria RAM?',a:['memtest86'],pts:15},{q:'Que refrigeracion usa liquido?',a:['refrigeracion liquida'],pts:15},{q:'Que significa SATA?',a:['serial ata'],pts:15},{q:'Que bateria mantiene la configuracion de la BIOS?',a:['pila cmos'],pts:15},{q:'Que tecnologia Intel permite virtualizacion hardware?',a:['vt-x'],pts:15},{q:'Que interfaz usan los SSD modernos de alta velocidad?',a:['nvme','m.2'],pts:15},{q:'Que mide la velocidad de transferencia de un disco?',a:['velocidad de lectura escritura'],pts:15}],
  montaje_dificil:[{q:'Que version de PCIe ofrece 16 GT/s por carril?',a:['pcie 4.0'],pts:20},{q:'Que RAID es de mirroring puro?',a:['raid 1'],pts:20},{q:'Que herramienta muestra temperaturas en tiempo real?',a:['hwmonitor','hwinfo'],pts:20},{q:'Que socket usa AMD Ryzen 5000?',a:['am4'],pts:20},{q:'Que tecnologia overclockea la RAM automaticamente?',a:['xmp'],pts:20},{q:'Que programa hace test de estres a la GPU?',a:['furmark'],pts:20},{q:'Que indica 1 pitido largo y 3 cortos en BIOS Award?',a:['error de tarjeta grafica'],pts:20},{q:'Que es el throttling en una CPU?',a:['reduccion de velocidad por temperatura'],pts:20},{q:'Que es un POST?',a:['power on self test'],pts:20},{q:'Que herramienta mide la continuidad de un cable?',a:['multimetro'],pts:20}],
  sistemas_facil:[{q:'Que SO de Microsoft es el mas reciente?',a:['windows 11'],pts:10},{q:'Que SO libre esta basado en Unix?',a:['linux'],pts:10},{q:'Que comando muestra la configuracion de red en Windows?',a:['ipconfig'],pts:10},{q:'Que sistema de archivos usa Windows por defecto?',a:['ntfs'],pts:10},{q:'Que comando lista directorios en Linux?',a:['ls'],pts:10},{q:'Que gestor de arranque es comun en Linux?',a:['grub'],pts:10},{q:'Que comando limpia la pantalla en Linux?',a:['clear'],pts:10},{q:'Que atajo copia en Windows?',a:['ctrl c'],pts:10},{q:'Que comando muestra procesos en Windows?',a:['tasklist'],pts:10},{q:'Que extension tienen los scripts de PowerShell?',a:['.ps1'],pts:10}],
  sistemas_medio:[{q:'Que comando muestra procesos en Linux?',a:['ps','top'],pts:15},{q:'Que herramienta repara el sistema de archivos en Windows?',a:['chkdsk'],pts:15},{q:'Que comando cambia permisos en Linux?',a:['chmod'],pts:15},{q:'Que sistema de archivos usa Linux por defecto?',a:['ext4'],pts:15},{q:'Que herramienta ve eventos en Windows?',a:['visor de eventos'],pts:15},{q:'Que comando muestra espacio en disco en Linux?',a:['df'],pts:15},{q:'Que comando reinicia Windows por CMD?',a:['shutdown /r'],pts:15},{q:'Que registro almacena config de usuario en Windows?',a:['hkey_current_user','hkcu'],pts:15},{q:'Que comando crea un directorio en Linux?',a:['mkdir'],pts:15},{q:'Que variable de entorno contiene las rutas de ejecutables?',a:['path'],pts:15}],
  sistemas_dificil:[{q:'Que comando sincroniza directorios en Linux?',a:['rsync'],pts:20},{q:'Que comando modifica la tabla de particiones en Linux?',a:['fdisk','parted'],pts:20},{q:'Que comando comprueba integridad del sistema en Windows?',a:['sfc /scannow'],pts:20},{q:'Que demonio gestiona los logs en Linux?',a:['syslog','rsyslog'],pts:20},{q:'Que comando configura interfaces de red en Linux?',a:['ip','ifconfig'],pts:20},{q:'Que modo de Windows carga solo drivers esenciales?',a:['modo seguro'],pts:20},{q:'Que herramienta monitoriza rendimiento en Windows?',a:['performance monitor','perfmon'],pts:20},{q:'Que comando muestra la ruta hasta un host?',a:['tracert','traceroute'],pts:20},{q:'Que es el kernel?',a:['nucleo del sistema operativo'],pts:20},{q:'Que fichero de Linux contiene usuarios del sistema?',a:['/etc/passwd'],pts:20}],
  ofimatica_facil:[{q:'Que programa de Microsoft sirve para hojas de calculo?',a:['excel'],pts:10},{q:'Que programa se usa para presentaciones en Microsoft?',a:['powerpoint'],pts:10},{q:'Que programa de Microsoft procesa textos?',a:['word'],pts:10},{q:'Que atajo guarda un documento en cualquier programa?',a:['ctrl s'],pts:10},{q:'Que funcion de Excel suma un rango de celdas?',a:['sum','suma'],pts:10},{q:'Que programa libre es alternativa gratuita a Office?',a:['libreoffice'],pts:10},{q:'Que extension tienen documentos de Word modernos?',a:['.docx'],pts:10},{q:'Que atajo imprime el documento actual?',a:['ctrl p'],pts:10},{q:'Que programa de Microsoft gestiona correo y calendario?',a:['outlook'],pts:10},{q:'Que formato de Word es plantilla reutilizable?',a:['.dotx'],pts:10}],
  ofimatica_medio:[{q:'Que funcion de Excel busca valores en tablas?',a:['vlookup','buscarv'],pts:15},{q:'Que funcion condicional basica tiene Excel?',a:['if','si'],pts:15},{q:'Que funcion de Excel cuenta celdas no vacias?',a:['counta','contara'],pts:15},{q:'Que herramienta de Word fusiona documentos con datos?',a:['combinar correspondencia'],pts:15},{q:'Como se escribe una referencia absoluta en Excel?',a:['$a$1'],pts:15},{q:'Que herramienta de Excel analiza tendencias visualmente?',a:['grafico'],pts:15},{q:'Que herramienta revisa la ortografia en Word?',a:['revision','f7'],pts:15},{q:'Que extension es una presentacion de solo lectura en PPT?',a:['.ppsx'],pts:15},{q:'Que funcion de Excel devuelve la fecha actual?',a:['today','hoy'],pts:15},{q:'Que vista de PowerPoint muestra miniaturas de diapositivas?',a:['clasificador de diapositivas'],pts:15}],
  ofimatica_dificil:[{q:'Que lenguaje se usa para programar macros en Office?',a:['vba'],pts:20},{q:'Que herramienta de Excel permite analisis de datos avanzado?',a:['tabla dinamica'],pts:20},{q:'Que funcion de Excel combina texto de celdas?',a:['concatenate','concatenar','concat'],pts:20},{q:'Que formato usa la base de datos Access?',a:['.accdb'],pts:20},{q:'Que combinacion de funciones permite busquedas avanzadas?',a:['index match'],pts:20},{q:'Que herramienta de Word compara dos versiones de un doc?',a:['comparar'],pts:20},{q:'Que funcion de Excel extrae texto del centro de una cadena?',a:['mid'],pts:20},{q:'Que caracteristica de Word protege el documento de edicion?',a:['restringir edicion'],pts:20},{q:'Que complemento de Office crea diagramas graficos?',a:['smartart'],pts:20},{q:'Que tipo de referencia en Excel no cambia al copiar?',a:['absoluta'],pts:20}],
  redes_facil:[{q:'Que topologia conecta dispositivos a un punto central?',a:['estrella'],pts:10},{q:'Que dispositivo conecta equipos en una red LAN?',a:['switch'],pts:10},{q:'Que protocolo asigna IP automaticamente?',a:['dhcp'],pts:10},{q:'Que herramienta prueba la conectividad entre equipos?',a:['ping'],pts:10},{q:'Que mascara tiene una red clase C?',a:['255.255.255.0'],pts:10},{q:'Que dispositivo separa y conecta distintas redes?',a:['router'],pts:10},{q:'Que servicio traduce nombres de dominio a IP?',a:['dns'],pts:10},{q:'Que puerto usa el protocolo HTTP?',a:['80'],pts:10},{q:'Que cable es mas comun en redes de cobre?',a:['utp cat5e','cat5e'],pts:10},{q:'Que direccion IP es de loopback?',a:['127.0.0.1'],pts:10}],
  redes_medio:[{q:'Que capa del modelo OSI maneja el enrutamiento IP?',a:['red','capa 3'],pts:15},{q:'Que protocolo previene bucles en redes de capa 2?',a:['stp'],pts:15},{q:'Que comando muestra la tabla ARP en Windows?',a:['arp -a'],pts:15},{q:'Que VLAN es la nativa por defecto en Cisco?',a:['vlan 1'],pts:15},{q:'Que estandar define el protocolo Ethernet?',a:['ieee 802.3'],pts:15},{q:'Que puerto usa HTTPS?',a:['443'],pts:15},{q:'Que mascara de subred en CIDR es /24?',a:['255.255.255.0'],pts:15},{q:'Que protocolo resuelve IPs a MACs?',a:['arp'],pts:15},{q:'Que tipo de IPv6 equivale a 127.0.0.1?',a:['::1'],pts:15},{q:'Que herramienta analiza el trafico de red?',a:['wireshark'],pts:15}],
  redes_dificil:[{q:'Que tipo de NAT traduce multiples IPs privadas con un solo puerto?',a:['pat'],pts:20},{q:'Que version mejorada de STP converge mas rapido?',a:['rstp'],pts:20},{q:'Que tecnologia agrega multiples enlaces fisicos en uno logico?',a:['etherchannel','lacp'],pts:20},{q:'Que protocolo autentica dispositivos en la red por puerto?',a:['802.1x'],pts:20},{q:'Que herramienta de Cisco descubre vecinos directos?',a:['cdp'],pts:20},{q:'Que protocolo de enrutamiento interior usa metricas compuestas?',a:['eigrp'],pts:20},{q:'Que tipo de ataque satura una red con trafico?',a:['ddos'],pts:20},{q:'Que es la segmentacion de red mediante VLANs?',a:['division logica de la red'],pts:20},{q:'Que permite el NAT en redes domesticas?',a:['compartir ip publica entre varios dispositivos'],pts:20},{q:'Que protocolo encripta la gestion de equipos de red?',a:['ssh'],pts:20}],
  ingles_facil:[{q:'Como se dice ordenador en ingles?',a:['computer'],pts:10},{q:'Como se dice raton en ingles?',a:['mouse'],pts:10},{q:'Como se dice teclado en ingles?',a:['keyboard'],pts:10},{q:'Como se dice pantalla o monitor en ingles?',a:['screen','monitor'],pts:10},{q:'Como se dice imprimir en ingles?',a:['print'],pts:10},{q:'Como se dice archivo en ingles?',a:['file'],pts:10},{q:'Como se dice carpeta en ingles?',a:['folder'],pts:10},{q:'Como se dice red en ingles?',a:['network'],pts:10},{q:'Como se dice disco duro en ingles?',a:['hard drive','hard disk'],pts:10},{q:'Como se dice memoria RAM en ingles?',a:['ram','random access memory'],pts:10}],
  ingles_medio:[{q:'Como se dice configuracion en ingles?',a:['configuration','settings'],pts:15},{q:'Como se dice soporte tecnico en ingles?',a:['technical support'],pts:15},{q:'Como se dice contrasena en ingles?',a:['password'],pts:15},{q:'Como se dice actualizacion en ingles?',a:['update'],pts:15},{q:'Como se dice instalacion en ingles?',a:['installation','setup'],pts:15},{q:'Como se dice usuario en ingles?',a:['user'],pts:15},{q:'Como se dice copia de seguridad en ingles?',a:['backup'],pts:15},{q:'Como se dice cortafuegos en ingles?',a:['firewall'],pts:15},{q:'Como se dice almacenamiento en ingles?',a:['storage'],pts:15},{q:'Como se dice red inalambrica en ingles?',a:['wireless network','wifi'],pts:15}],
  ingles_dificil:[{q:'Como se dice solucion de problemas en ingles?',a:['troubleshooting'],pts:20},{q:'Como se dice virtualizacion en ingles?',a:['virtualization'],pts:20},{q:'Como se dice infraestructura en ingles?',a:['infrastructure'],pts:20},{q:'Como se dice escalabilidad en ingles?',a:['scalability'],pts:20},{q:'Como se dice almacenamiento en la nube en ingles?',a:['cloud storage'],pts:20},{q:'Como se dice rendimiento en ingles?',a:['performance'],pts:20},{q:'Como se dice ciberseguridad en ingles?',a:['cybersecurity'],pts:20},{q:'Como se dice interfaz de usuario en ingles?',a:['user interface'],pts:20},{q:'Como se dice mantenimiento preventivo en ingles?',a:['preventive maintenance'],pts:20},{q:'Como se dice ancho de banda en ingles?',a:['bandwidth'],pts:20}],
  empleabilidad_facil:[{q:'Que documento presenta tus habilidades y experiencia?',a:['curriculum','cv'],pts:10},{q:'Que red social profesional es mas usada en Espana?',a:['linkedin'],pts:10},{q:'Que carta se envia junto al CV?',a:['carta de presentacion'],pts:10},{q:'Que habilidad blanda es trabajar bien en equipo?',a:['teamwork','trabajo en equipo'],pts:10},{q:'Que actitud positiva ante problemas se valora?',a:['proactividad'],pts:10},{q:'Que red de contactos profesionales es importante?',a:['networking'],pts:10},{q:'Que documento prueba tu formacion academica?',a:['titulo','certificado'],pts:10},{q:'Que actitud muestra cumplir con los plazos?',a:['responsabilidad','compromiso'],pts:10},{q:'Que empresa ofrece empleo temporal?',a:['ett','empresa de trabajo temporal'],pts:10},{q:'Que organismo gestiona el desempleo en Espana?',a:['sepe'],pts:10}],
  empleabilidad_medio:[{q:'Que tecnica busca empleo de forma activa?',a:['busqueda activa de empleo'],pts:15},{q:'Que tipo de entrevista es con varias personas a la vez?',a:['entrevista grupal','entrevista colectiva'],pts:15},{q:'Que actitud es adaptarse a los cambios del entorno?',a:['flexibilidad','adaptabilidad'],pts:15},{q:'Que tipo de contrato no tiene fecha de fin?',a:['contrato indefinido','contrato fijo'],pts:15},{q:'Que actitud significa aprender continuamente?',a:['formacion continua'],pts:15},{q:'Que habilidad es comunicarse de forma efectiva?',a:['comunicacion'],pts:15},{q:'Que herramienta analiza fortalezas y debilidades?',a:['dafo','foda'],pts:15},{q:'Que documento planifica tus objetivos profesionales?',a:['plan de carrera'],pts:15},{q:'Que competencia es gestionar bien el tiempo?',a:['gestion del tiempo'],pts:15},{q:'Que tipo de empleo es trabajar por cuenta propia?',a:['autonomo','freelance'],pts:15}],
  empleabilidad_dificil:[{q:'Que metodo STAR se usa en entrevistas?',a:['situacion tarea accion resultado'],pts:20},{q:'Que competencia es liderar e inspirar equipos?',a:['liderazgo'],pts:20},{q:'Que actitud es gestionar el estres y recuperarse?',a:['resiliencia'],pts:20},{q:'Que tecnica de productividad usa intervalos de 25 min?',a:['tecnica pomodoro'],pts:20},{q:'Que es el employer branding?',a:['marca empleadora'],pts:20},{q:'Que competencia es negociar para lograr acuerdos?',a:['negociacion'],pts:20},{q:'Que es el mentoring profesional?',a:['guia y apoyo de un profesional experto'],pts:20},{q:'Que habilidad es entender y gestionar emociones?',a:['inteligencia emocional'],pts:20},{q:'Que es el upskilling?',a:['mejorar habilidades actuales'],pts:20},{q:'Que significa PRL en el entorno laboral?',a:['prevencion de riesgos laborales'],pts:20}],
  sistemasred_facil:[{q:'Que SO para servidores desarrolla Microsoft?',a:['windows server'],pts:10},{q:'Que servicio asigna IPs en Windows Server?',a:['dhcp'],pts:10},{q:'Que protocolo resuelve nombres en una red?',a:['dns'],pts:10},{q:'Que protocolo usa Active Directory para autenticacion?',a:['kerberos'],pts:10},{q:'Que herramienta administra usuarios en Active Directory?',a:['usuarios y equipos de active directory','aduc'],pts:10},{q:'Que servicio comparte archivos en red Windows?',a:['compartir archivos','smb'],pts:10},{q:'Que unidad organizativa se crea por defecto en AD?',a:['users'],pts:10},{q:'Que comando muestra el nombre del equipo en Linux?',a:['hostname'],pts:10},{q:'Que distribucion Linux es popular para servidores?',a:['ubuntu server','debian','centos'],pts:10},{q:'Que fichero de Linux muestra interfaces de red activas?',a:['/etc/network/interfaces','nmcli'],pts:10}],
  sistemasred_medio:[{q:'Que comando actualiza paquetes en Debian/Ubuntu?',a:['apt update','apt-get update'],pts:15},{q:'Que puerto usa LDAP?',a:['389'],pts:15},{q:'Que rol convierte un servidor en controlador de dominio?',a:['active directory domain services','adds'],pts:15},{q:'Que fichero de Linux contiene la configuracion DNS?',a:['/etc/resolv.conf'],pts:15},{q:'Que GPO aplica configuraciones a todos los usuarios del dominio?',a:['default domain policy'],pts:15},{q:'Que comando de Linux instala un paquete?',a:['apt install'],pts:15},{q:'Que herramienta administra el servidor de forma remota?',a:['escritorio remoto','rdp'],pts:15},{q:'Que protocolo sincroniza la hora en Active Directory?',a:['ntp'],pts:15},{q:'Que fichero de Linux define los grupos del sistema?',a:['/etc/group'],pts:15},{q:'Que comando muestra los procesos mas activos en Linux?',a:['top','htop'],pts:15}],
  sistemasred_dificil:[{q:'Que es un bosque en Active Directory?',a:['conjunto de dominios que comparten un esquema'],pts:20},{q:'Que comando PowerShell crea un usuario en AD?',a:['new-aduser'],pts:20},{q:'Que replica de AD contiene todos los objetos del bosque?',a:['global catalog'],pts:20},{q:'Que comando de Linux cambia el propietario de un fichero?',a:['chown'],pts:20},{q:'Que puerto usa LDAP cifrado con SSL?',a:['636'],pts:20},{q:'Que es un trust entre dominios?',a:['relacion que permite autenticacion entre dominios'],pts:20},{q:'Que herramienta de Linux permite gestion centralizada de paquetes?',a:['apt','yum','dnf'],pts:20},{q:'Que es un snapshot en una maquina virtual?',a:['instantanea del estado de la maquina'],pts:20},{q:'Que comando PowerShell lista todos los usuarios de AD?',a:['get-aduser'],pts:20},{q:'Que servicio de Windows sincroniza ficheros entre servidores?',a:['dfs','sistema de archivos distribuido'],pts:20}],
  seguridad_facil:[{q:'Que malware se propaga automaticamente por la red?',a:['gusano','worm'],pts:10},{q:'Que software protege contra virus?',a:['antivirus'],pts:10},{q:'Que tecnica usa correos falsos para robar datos?',a:['phishing'],pts:10},{q:'Que dispositivo filtra el trafico no autorizado?',a:['firewall','cortafuegos'],pts:10},{q:'Que protocolo cifra el trafico web?',a:['https'],pts:10},{q:'Que ataque satura un servidor con peticiones?',a:['ddos','denegacion de servicio'],pts:10},{q:'Que es un backup?',a:['copia de seguridad'],pts:10},{q:'Que tipo de contrasena es mas segura?',a:['larga y compleja'],pts:10},{q:'Que ataque intercepta comunicaciones entre dos partes?',a:['man in the middle','hombre en el medio'],pts:10},{q:'Que es el malware?',a:['software malicioso'],pts:10}],
  seguridad_medio:[{q:'Que algoritmo de cifrado simetrico es mas comun hoy?',a:['aes'],pts:15},{q:'Que es un honeypot en seguridad?',a:['sistema senuelo para detectar atacantes'],pts:15},{q:'Que estandar inalambrico es mas seguro actualmente?',a:['wpa3','wpa2'],pts:15},{q:'Que ataque inyecta codigo en bases de datos?',a:['sql injection'],pts:15},{q:'Que es la autenticacion de dos factores?',a:['2fa','autenticacion de doble factor'],pts:15},{q:'Que es un certificado digital?',a:['documento electronico que vincula identidad con clave publica'],pts:15},{q:'Que herramienta analiza paquetes de red?',a:['wireshark'],pts:15},{q:'Que es el cifrado asimetrico?',a:['usa clave publica y privada'],pts:15},{q:'Que es un IDS?',a:['sistema de deteccion de intrusiones'],pts:15},{q:'Que es el principio de minimo privilegio?',a:['dar solo los permisos necesarios'],pts:15}],
  seguridad_dificil:[{q:'Que es un rootkit?',a:['malware que oculta su presencia en el sistema'],pts:20},{q:'Que ataque prueba todas las combinaciones posibles?',a:['fuerza bruta'],pts:20},{q:'Que es un ataque de diccionario?',a:['probar contrasenas comunes de una lista'],pts:20},{q:'Que protocolo seguro se usa para administracion remota?',a:['ssh'],pts:20},{q:'Que es un firewall stateful?',a:['analiza el estado de las conexiones'],pts:20},{q:'Que es un ataque de replay?',a:['reenvio de datos validos interceptados'],pts:20},{q:'Quien emite los certificados digitales?',a:['autoridad de certificacion','ca'],pts:20},{q:'Que diferencia hay entre cifrado simetrico y asimetrico?',a:['simetrico usa misma clave, asimetrico publica y privada'],pts:20},{q:'Que es el pentesting?',a:['prueba de penetracion o hacking etico'],pts:20},{q:'Que es la ingenieria social en ciberseguridad?',a:['manipular personas para obtener informacion'],pts:20}],
  servicios_facil:[{q:'Que servicio web usa el puerto 80?',a:['http'],pts:10},{q:'Que protocolo envia correo electronico?',a:['smtp'],pts:10},{q:'Que servicio transfiere archivos entre equipos?',a:['ftp'],pts:10},{q:'Que servicio asigna IPs automaticamente en la red?',a:['dhcp'],pts:10},{q:'Que servicio traduce nombres de dominio a IP?',a:['dns'],pts:10},{q:'Que puerto usa HTTPS?',a:['443'],pts:10},{q:'Que protocolo descarga correos al cliente de correo?',a:['pop3'],pts:10},{q:'Que protocolo mantiene correos en el servidor?',a:['imap'],pts:10},{q:'Que servidor web de Microsoft se usa en Windows Server?',a:['iis','internet information services'],pts:10},{q:'Que permite el acceso remoto al escritorio en Windows?',a:['rdp','remote desktop'],pts:10}],
  servicios_medio:[{q:'Que comando de Linux inicia un servicio?',a:['systemctl start'],pts:15},{q:'Que servidor web open source es el mas popular del mundo?',a:['apache'],pts:15},{q:'Que protocolo ligero se usa para consultar directorios?',a:['ldap'],pts:15},{q:'Que zona DNS contiene los registros de correo?',a:['mx'],pts:15},{q:'Que registro DNS apunta un nombre a otro nombre?',a:['cname'],pts:15},{q:'Que comando verifica la resolucion DNS?',a:['nslookup','dig'],pts:15},{q:'Que es un servidor proxy?',a:['intermediario entre cliente e internet'],pts:15},{q:'Que protocolo cifrado se usa para SSH?',a:['ssh'],pts:15},{q:'Que directiva de Apache define sitios virtuales?',a:['virtualhost'],pts:15},{q:'Que servicio autentica mediante tickets Kerberos?',a:['kerberos','active directory'],pts:15}],
  servicios_dificil:[{q:'Que es un balanceador de carga?',a:['distribuye trafico entre varios servidores'],pts:20},{q:'Que es un proxy inverso?',a:['proxy que protege servidores internos'],pts:20},{q:'Que permite la reserva DHCP?',a:['asignar siempre la misma ip a un equipo por su mac'],pts:20},{q:'Que es DNSSEC?',a:['extension que anade seguridad al dns'],pts:20},{q:'Que es el protocolo RADIUS?',a:['autenticacion para acceso a redes'],pts:20},{q:'Que hace el servicio NTP?',a:['sincroniza la hora entre equipos'],pts:20},{q:'Que es un cluster de alta disponibilidad?',a:['grupo de servidores que se sustituyen si uno falla'],pts:20},{q:'Que diferencia hay entre zona primaria y secundaria en DNS?',a:['primaria es editable, secundaria es copia de solo lectura'],pts:20},{q:'Que significa CDN?',a:['red de distribucion de contenidos'],pts:20},{q:'Que es la virtualizacion de servidores?',a:['ejecutar multiples servidores virtuales en un fisico'],pts:20}],
  web_facil:[{q:'Que lenguaje define la estructura de una pagina web?',a:['html'],pts:10},{q:'Que lenguaje define el estilo visual de una web?',a:['css'],pts:10},{q:'Que lenguaje es el principal del frontend web?',a:['javascript'],pts:10},{q:'Que etiqueta HTML crea un enlace?',a:['a','a href'],pts:10},{q:'Que etiqueta HTML muestra una imagen?',a:['img'],pts:10},{q:'Que CMS es mas popular para crear blogs?',a:['wordpress'],pts:10},{q:'Que extension tienen los ficheros JavaScript?',a:['.js'],pts:10},{q:'Que etiqueta HTML crea un parrafo?',a:['p'],pts:10},{q:'Que significa HTML?',a:['hypertext markup language'],pts:10},{q:'Que significa CSS?',a:['cascading style sheets'],pts:10}],
  web_medio:[{q:'Que framework JavaScript creo Google?',a:['angular'],pts:15},{q:'Que libreria de JavaScript simplifica el DOM?',a:['jquery'],pts:15},{q:'Que propiedad CSS alinea el texto horizontalmente?',a:['text-align'],pts:15},{q:'Que base de datos se usa tipicamente con PHP?',a:['mysql'],pts:15},{q:'Que lenguaje de servidor es mas comun en web?',a:['php'],pts:15},{q:'Que tipo de diseno se adapta a cualquier pantalla?',a:['responsive'],pts:15},{q:'Que metodo HTTP envia datos de un formulario?',a:['post'],pts:15},{q:'Que significa API?',a:['application programming interface'],pts:15},{q:'Que framework de CSS es muy popular para diseno responsive?',a:['bootstrap'],pts:15},{q:'Que funcion de JavaScript muestra un dialogo de alerta?',a:['alert'],pts:15}],
  web_dificil:[{q:'Que arquitectura separa frontend y backend mediante APIs?',a:['spa','single page application'],pts:20},{q:'Que formato de datos ligero se usa en APIs REST?',a:['json'],pts:20},{q:'Que tecnologia permite comunicacion bidireccional en tiempo real?',a:['websockets'],pts:20},{q:'Que framework CSS usa clases de utilidad?',a:['tailwind'],pts:20},{q:'Que ataque web inyecta scripts maliciosos en paginas?',a:['xss','cross site scripting'],pts:20},{q:'Que es el renderizado del lado del servidor?',a:['ssr','server side rendering'],pts:20},{q:'Que herramienta permite probar APIs REST?',a:['postman','insomnia'],pts:20},{q:'Que significa CORS en el contexto web?',a:['cross origin resource sharing'],pts:20},{q:'Que es un token JWT?',a:['json web token para autenticacion'],pts:20},{q:'Que es el DOM?',a:['document object model'],pts:20}],
  empleabilidad2_facil:[{q:'Que documento recoge derechos y deberes del trabajador?',a:['contrato de trabajo'],pts:10},{q:'Que contrato tiene una duracion determinada?',a:['contrato temporal'],pts:10},{q:'Que organismo gestiona el desempleo en Espana?',a:['sepe'],pts:10},{q:'Que prestacion recibe un trabajador al jubilarse?',a:['pension de jubilacion'],pts:10},{q:'Que jornada laboral es de 40 horas semanales?',a:['jornada completa'],pts:10},{q:'Que documento cobra el trabajador cada mes?',a:['nomina'],pts:10},{q:'Que es el salario minimo interprofesional?',a:['smi'],pts:10},{q:'Que tipo de baja es por enfermedad?',a:['incapacidad temporal','baja medica'],pts:10},{q:'Que es un finiquito?',a:['pago al finalizar el contrato'],pts:10},{q:'Que derechos incluye una baja por maternidad?',a:['permiso de maternidad','baja maternal'],pts:10}],
  empleabilidad2_medio:[{q:'Que contrato fomenta la contratacion de jovenes en formacion?',a:['contrato en practicas','contrato formacion'],pts:15},{q:'Que es un convenio colectivo?',a:['acuerdo que regula condiciones laborales de un sector'],pts:15},{q:'Que porcentaje del salario puede ser en especie como maximo?',a:['30%'],pts:15},{q:'Que es una ETT?',a:['empresa de trabajo temporal'],pts:15},{q:'Que es el despido disciplinario?',a:['despido por falta grave del trabajador'],pts:15},{q:'Que es la conciliacion laboral y familiar?',a:['equilibrio entre vida profesional y personal'],pts:15},{q:'Que es un ERTE?',a:['expediente de regulacion temporal de empleo'],pts:15},{q:'Que organismo media en conflictos laborales?',a:['cmac','smac'],pts:15},{q:'Que es la base de cotizacion?',a:['cantidad sobre la que se calculan las cotizaciones'],pts:15},{q:'Que es el teletrabajo?',a:['trabajo a distancia mediante tecnologia'],pts:15}],
  empleabilidad2_dificil:[{q:'Que diferencia hay entre autonomo y asalariado?',a:['autonomo trabaja por cuenta propia, asalariado por cuenta ajena'],pts:20},{q:'Que es la negociacion colectiva?',a:['dialogo entre empresa y sindicatos para fijar condiciones'],pts:20},{q:'Que es un plan de igualdad?',a:['medidas para garantizar igualdad de trato en la empresa'],pts:20},{q:'Que es el SMI en 2024?',a:['salario minimo interprofesional'],pts:20},{q:'Que es el periodo de prueba en un contrato?',a:['tiempo inicial para evaluar al trabajador'],pts:20},{q:'Que prestacion cubre el cese de actividad de un autonomo?',a:['cese de actividad'],pts:20},{q:'Que significa PRL?',a:['prevencion de riesgos laborales'],pts:20},{q:'Que es el upskilling en el entorno laboral?',a:['mejora de habilidades del trabajador'],pts:20},{q:'Que es la evaluacion de desempeno?',a:['revision periodica del rendimiento del trabajador'],pts:20},{q:'Que es un headhunter?',a:['cazatalentos o reclutador especializado'],pts:20}],
  proyecto_facil:[{q:'Que documento describe el alcance de un proyecto?',a:['acta de proyecto','project charter'],pts:10},{q:'Que herramienta visual representa tareas en el tiempo?',a:['diagrama de gantt'],pts:10},{q:'Que reunion marca el inicio formal de un proyecto?',a:['kickoff'],pts:10},{q:'Que rol lidera el equipo de proyecto?',a:['jefe de proyecto','project manager'],pts:10},{q:'Que documento recoge los requisitos del proyecto?',a:['especificacion de requisitos'],pts:10},{q:'Que tecnica divide el trabajo en paquetes mas pequenos?',a:['edt','estructura de desglose del trabajo'],pts:10},{q:'Que es un entregable en un proyecto?',a:['producto o resultado del proyecto'],pts:10},{q:'Que fase define los recursos necesarios?',a:['planificacion'],pts:10},{q:'Que es un hito en un proyecto?',a:['evento importante del proyecto'],pts:10},{q:'Que tipo de proyecto tiene fecha de inicio y fin definida?',a:['proyecto temporal'],pts:10}],
  proyecto_medio:[{q:'Que metodologia agil usa sprints de 2-4 semanas?',a:['scrum'],pts:15},{q:'Que herramienta registra incidencias y tareas?',a:['jira','trello'],pts:15},{q:'Que es un stakeholder?',a:['persona interesada en el proyecto'],pts:15},{q:'Que documento evalua la viabilidad economica del proyecto?',a:['estudio de viabilidad'],pts:15},{q:'Que fase verifica que el producto cumple los requisitos?',a:['pruebas','testing'],pts:15},{q:'Que es el alcance de un proyecto?',a:['trabajo que se debe realizar'],pts:15},{q:'Que tecnica prioriza requisitos en agil?',a:['moscow'],pts:15},{q:'Que documento recoge las lecciones aprendidas?',a:['informe de cierre'],pts:15},{q:'Que es la gestion del riesgo?',a:['identificar y gestionar riesgos del proyecto'],pts:15},{q:'Que tipo de metodologia sigue un orden secuencial?',a:['waterfall','cascada'],pts:15}],
  proyecto_dificil:[{q:'Que certificacion internacional existe para jefes de proyecto?',a:['pmp','prince2'],pts:20},{q:'Que tecnica usa estimaciones optimista y pesimista?',a:['pert'],pts:20},{q:'Que es el valor ganado en gestion de proyectos?',a:['tecnica para medir el desempeno del proyecto'],pts:20},{q:'Que es la ruta critica de un proyecto?',a:['secuencia de tareas que determina la duracion total'],pts:20},{q:'Que diferencia hay entre proyecto y operacion continua?',a:['el proyecto es temporal, la operacion es continua'],pts:20},{q:'Que es un plan de contingencia?',a:['plan de accion ante riesgos identificados'],pts:20},{q:'Que es el acta de cierre de un proyecto?',a:['documento formal que finaliza el proyecto'],pts:20},{q:'Que significa OKR en gestion de proyectos?',a:['objectives and key results'],pts:20},{q:'Que es el backlog en Scrum?',a:['lista priorizada de requisitos del producto'],pts:20},{q:'Que rol en Scrum gestiona el backlog del producto?',a:['product owner'],pts:20}]
};

const SHOP_ITEMS = [
  {id:'h1',name:'Sombrero Tecnico',cost:75,type:'hat',icon:'&#127913;'},
  {id:'h2',name:'Corona de Experto',cost:150,type:'hat',icon:'&#128081;'},
  {id:'h3',name:'Gorro Graduacion',cost:100,type:'hat',icon:'&#127891;'},
  {id:'g1',name:'Gafas Ciberseguridad',cost:60,type:'glasses',icon:'&#128374;'},
  {id:'g2',name:'Gafas Realidad Virtual',cost:90,type:'glasses',icon:'&#128083;'},
  {id:'i1',name:'Maletin de Herramientas',cost:120,type:'item',icon:'&#128188;'},
  {id:'i2',name:'Kit de Reparacion',cost:135,type:'item',icon:'&#128296;'}
];

const ASM_QS = [
  {id:1,cat:'IDENTIFICACION',icon:'&#128421;',title:'CPU',desc:'Componente cuadrado con pines. Lleva disipador encima.',
   q:'Cual es la funcion principal de la CPU?',
   opts:[{t:'CPU - Procesa instrucciones y controla el sistema',ic:'&#9889;'},{t:'GPU - Renderiza imagenes y graficos 3D',ic:'&#127918;'},{t:'Chipset - Gestiona comunicacion entre componentes',ic:'&#128268;'},{t:'VRM - Regula el voltaje para la CPU',ic:'&#9889;'}],
   cor:0,hint:'Es el cerebro del ordenador.',pts:25,coins:15,exp:'La CPU ejecuta instrucciones, realiza calculos y coordina el resto de componentes del sistema.'},
  {id:2,cat:'MEMORIA',icon:'&#128190;',title:'Memoria RAM',desc:'Tarjeta rectangular con chips negros y una muesca.',
   q:'Que caracteristica define principalmente a la RAM?',
   opts:[{t:'Es volatil: pierde datos al apagar',ic:'&#9889;'},{t:'Almacena datos permanentemente',ic:'&#128189;'},{t:'Guarda el sistema operativo',ic:'&#128187;'},{t:'Solo la usa la tarjeta grafica',ic:'&#127918;'}],
   cor:0,hint:'Si no guardas antes de apagar, lo pierdes.',pts:20,coins:12,exp:'La RAM es volatil, muy rapida, y almacena temporalmente los datos que la CPU necesita en tiempo real.'},
  {id:3,cat:'HERRAMIENTAS',icon:'&#128737;',title:'Pulsera antiestatica',desc:'Brazalete ajustable con cable y pinza a tierra.',
   q:'Para que se usa la pulsera antiestatica?',
   opts:[{t:'Proteger de descargas electrostaticas (ESD)',ic:'&#9889;'},{t:'Medir la temperatura de la CPU',ic:'&#127777;'},{t:'Iluminar el interior del gabinete',ic:'&#128161;'},{t:'Limpiar el polvo acumulado',ic:'&#129529;'}],
   cor:0,hint:'La electricidad estatica puede fundir circuitos.',pts:15,coins:8,exp:'Descarga a tierra la electricidad estatica de tu cuerpo, evitando danar los componentes electronicos sensibles.'},
  {id:4,cat:'CONEXIONES',icon:'&#128268;',title:'Cable SATA',desc:'Cable plano con conectores en forma de L.',
   q:'Que dispositivos conecta principalmente el cable SATA?',
   opts:[{t:'Discos duros y unidades SSD SATA',ic:'&#128189;'},{t:'Tarjetas graficas dedicadas PCIe',ic:'&#127918;'},{t:'Ventiladores del gabinete',ic:'&#127744;'},{t:'Fuente de alimentacion a la placa',ic:'&#128267;'}],
   cor:0,hint:'Sustituyo a los antiguos cables IDE/PATA.',pts:20,coins:10,exp:'Los cables SATA transfieren datos entre la placa base y dispositivos de almacenamiento como HDD y SSD SATA.'},
  {id:5,cat:'DIAGNOSTICO',icon:'&#128266;',title:'Codigos POST',desc:'Secuencia de pitidos al encender el PC.',
   q:'Que indica un pitido largo y continuo al encender?',
   opts:[{t:'Problema con la memoria RAM',ic:'&#128190;'},{t:'Error en la tarjeta grafica',ic:'&#127918;'},{t:'CPU no detectada',ic:'&#128421;'},{t:'Teclado no conectado',ic:'&#9000;'}],
   cor:0,hint:'El error mas comun al montar un PC.',pts:25,coins:15,exp:'Un pitido largo continuo en BIOS Award/AMI indica fallo o ausencia de memoria RAM.'}
];

const CABLE_QS = [
  {id:1,title:'T568A',desc:'Ordena los cables segun el estandar T568A',colors:['verde-blanco','verde','naranja-blanco','azul','azul-blanco','naranja','marron-blanco','marron'],correct:[0,1,2,3,4,5,6,7],exp:'T568A: 1.Verde/blanco 2.Verde 3.Naranja/blanco 4.Azul 5.Azul/blanco 6.Naranja 7.Marron/blanco 8.Marron'},
  {id:2,title:'T568B',desc:'Ordena los cables segun T568B (el mas comun en Europa)',colors:['naranja-blanco','naranja','verde-blanco','azul','azul-blanco','verde','marron-blanco','marron'],correct:[0,1,2,3,4,5,6,7],exp:'T568B: 1.Naranja/blanco 2.Naranja 3.Verde/blanco 4.Azul 5.Azul/blanco 6.Verde 7.Marron/blanco 8.Marron'},
  {id:3,title:'Cable Cruzado',desc:'Conecta dos dispositivos iguales (PC a PC)',colors:['verde-blanco','verde','naranja-blanco','azul','azul-blanco','naranja','marron-blanco','marron'],correct:[0,1,2,3,4,5,6,7],exp:'El cable cruzado tiene un extremo T568A y el otro T568B, para conectar equipos del mismo tipo.'},
  {id:4,title:'Cable Recto',desc:'Conecta dispositivos distintos (PC a switch)',colors:['naranja-blanco','naranja','verde-blanco','azul','azul-blanco','verde','marron-blanco','marron'],correct:[0,1,2,3,4,5,6,7],exp:'El cable recto usa el mismo estandar en ambos extremos, generalmente T568B.'}
];

const MATCH_QS = [
  {t:'CPU',d:'Componente que ejecuta instrucciones, realiza calculos aritmeticos y logicos y coordina el sistema.'},
  {t:'RAM',d:'Memoria volatil de alta velocidad que almacena datos e instrucciones que la CPU necesita inmediatamente.'},
  {t:'SSD',d:'Unidad de almacenamiento no volatil con memoria flash, mucho mas rapida que un disco duro mecanico.'},
  {t:'Fuente de Alimentacion',d:'Convierte la corriente alterna de la red en corriente continua de bajo voltaje para los componentes.'},
  {t:'Placa Base',d:'Tarjeta principal que conecta y permite la comunicacion entre todos los componentes del sistema.'}
];

const MINI_QS = [
  {q:'Que puerto usa LDAP sin cifrar?',opts:['389','636','3268','3269'],cor:0},
  {q:'Que nivel de RAID combina striping con paridad distribuida?',opts:['RAID 3','RAID 5','RAID 6','RAID 10'],cor:1},
  {q:'Que protocolo replica las bases de datos de Active Directory?',opts:['LDAP','Kerberos','NTLM','DFS-R'],cor:3},
  {q:'Que comando de Linux modifica la tabla de rutas?',opts:['route','ip route','netstat','traceroute'],cor:1},
  {q:'Que zona DNS permite actualizaciones dinamicas seguras?',opts:['Zona primaria','Zona integrada en AD','Zona secundaria','Zona de stub'],cor:1}
];

const Store={_m:{},get(k){try{const v=localStorage.getItem(k);return v!==null?JSON.parse(v):null;}catch(e){return this._m[k]!==undefined?this._m[k]:null;}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v));}catch(e){this._m[k]=v;}},del(k){try{localStorage.removeItem(k);}catch(e){delete this._m[k];}}};
const UK='smrq_users',SK='smrq_sess';
function getUsers(){return Store.get(UK)||[];}
function saveUsers(u){Store.set(UK,u);}
function hashPw(p){let h=5381;for(let i=0;i<p.length;i++)h=((h<<5)+h)^p.charCodeAt(i);return(h>>>0).toString(36);}
function calcLvl(p){if(p>=1000)return'Maestro';if(p>=700)return'Experto+';if(p>=500)return'Experto';if(p>=300)return'Intermedio+';if(p>=200)return'Intermedio';if(p>=100)return'Principiante+';if(p>=50)return'Principiante';return'Novato';}
function defUnlocked(){return Object.keys(LEVELS).filter(k=>LEVELS[k].cost===0);}
function initSt(){return{totalPoints:0,coins:0,currentYear:'primero',unlockedLevels:defUnlocked(),completedLevels:[],ownedItems:[],equippedItems:{hat:null,glasses:null,item:null},qTimer:null,timerSecs:25,mgStats:{}};}
let GS=null,CU=null;
function $(i){return document.getElementById(i);}
function shuffle(a){const r=[...a];for(let i=r.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[r[i],r[j]]=[r[j],r[i]];}return r;}
function notify(msg,t){t=t||'in';const n=document.createElement('div');n.className='notif '+t;n.innerHTML='<i class="fas fa-'+(t==='ok'?'check-circle':t==='er'?'exclamation-circle':'info-circle')+'"></i><span>'+msg+'</span>';document.body.appendChild(n);setTimeout(function(){n.style.animation='nout .3s ease forwards';setTimeout(function(){n.remove();},350);},4000);}
function hideAll(){['sLevels','sMini','sQuiz','sAvatar','sAsm','sAsmRes','sMatch','sCable','sCableRes'].forEach(function(id){var el=$(id);if(el){el.classList.remove('on');el.style.display='';}});}
function showSec(id){hideAll();var el=$(id);if(el)el.classList.add('on');}
// AUTH
window.showTab=function(tab,btn){document.querySelectorAll('.ltab').forEach(function(t){t.classList.remove('on');});if(btn)btn.classList.add('on');$('fLogin').classList.toggle('on',tab==='login');$('fReg').classList.toggle('on',tab==='reg');document.querySelectorAll('.ferr').forEach(function(e){e.classList.remove('on');e.textContent='';});};
window.togglePw=function(id,btn){var inp=$(id);if(!inp)return;if(inp.type==='password'){inp.type='text';btn.innerHTML='<i class="fas fa-eye-slash"></i>';}else{inp.type='password';btn.innerHTML='<i class="fas fa-eye"></i>';}};
function showErr(id,msg){var e=$(id);if(e){e.textContent=msg;e.classList.add('on');}}
function regUser(name,user,email,pw){var users=getUsers();if(users.find(function(u){return u.u===user.toLowerCase();}))return{ok:false,field:'rUserErr',msg:'Usuario ya existe'};if(users.find(function(u){return u.e===email.toLowerCase();}))return{ok:false,field:'rEmailErr',msg:'Email ya registrado'};var u={id:Date.now().toString(),name:name,u:user.toLowerCase(),e:email.toLowerCase(),pw:hashPw(pw),state:initSt(),color:['#00f2ff','#7000ff','#00ff9d','#ff0055','#ffcc00'][Math.floor(Math.random()*5)],ini:name.trim().split(/\s+/).map(function(w){return w[0];}).join('').toUpperCase().slice(0,2)};users.push(u);saveUsers(users);return{ok:true,user:u};}
function loginUser(id,pw){var users=getUsers();var u=users.find(function(u){return u.u===id.toLowerCase()||u.e===id.toLowerCase();});if(!u)return{ok:false,field:'lErr',msg:'Usuario o contrasena incorrectos'};if(u.pw!==hashPw(pw))return{ok:false,field:'lErr',msg:'Usuario o contrasena incorrectos'};if(!u.state)u.state=initSt();var du=defUnlocked();du.forEach(function(k){if(!u.state.unlockedLevels.includes(k))u.state.unlockedLevels.push(k);});saveUsers(users);return{ok:true,user:u};}
function saveSess(){if(!CU)return;var users=getUsers();var idx=users.findIndex(function(u){return u.id===CU.id;});if(idx>=0){users[idx]=CU;saveUsers(users);}Store.set(SK,CU.id);}
function loadSess(){try{var id=Store.get(SK);if(!id)return false;var users=getUsers();if(!Array.isArray(users))return false;var u=users.find(function(u){return u.id===id;});if(!u||!u.state||!u.name)return false;CU=u;GS=u.state;if(!GS.unlockedLevels)GS.unlockedLevels=defUnlocked();if(!GS.completedLevels)GS.completedLevels=[];if(!GS.ownedItems)GS.ownedItems=[];if(!GS.equippedItems)GS.equippedItems={hat:null,glasses:null,item:null};return true;}catch(e){try{Store.del(SK);}catch(e2){}return false;}}
window.doLogin=function(){document.querySelectorAll('.ferr').forEach(function(e){e.classList.remove('on');});var id=$('lUser').value.trim(),pw=$('lPass').value;if(!id){showErr('lErr','Introduce tu usuario o email');return;}if(!pw){showErr('lPassErr','Introduce tu contrasena');return;}var r=loginUser(id,pw);if(r.ok)startGame(r.user);else showErr(r.field,r.msg);};
window.doReg=function(){document.querySelectorAll('.ferr').forEach(function(e){e.classList.remove('on');});var name=$('rName').value.trim(),user=$('rUser').value.trim(),email=$('rEmail').value.trim(),pw=$('rPass').value,pw2=$('rPass2').value;var ok=true;if(name.length<3){showErr('rNameErr','Minimo 3 caracteres');ok=false;}if(user.length<3){showErr('rUserErr','Minimo 3 caracteres');ok=false;}else if(!/^[a-zA-Z0-9_]+$/.test(user)){showErr('rUserErr','Solo letras, numeros y _');ok=false;}if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){showErr('rEmailErr','Email no valido');ok=false;}if(pw.length<6){showErr('rPassErr','Minimo 6 caracteres');ok=false;}if(pw!==pw2){showErr('rPass2Err','No coinciden');ok=false;}if(!ok)return;var r=regUser(name,user,email,pw);if(r.ok){startGame(r.user);notify('Bienvenido '+name,'ok');}else showErr(r.field,r.msg);};
window.doLogout=function(){if(!confirm('Cerrar sesion?'))return;saveSess();CU=null;GS=null;Store.del(SK);$('login').classList.remove('gone');$('game').classList.remove('show');$('lUser').value='';$('lPass').value='';showTab('login',document.querySelectorAll('.ltab')[0]);};
function startGame(user){CU=user;GS=user.state;saveSess();updateUI();$('login').classList.add('gone');$('game').classList.add('show');showMain('levels',document.querySelectorAll('.ntab')[0]);renderLevels();updateStats();updateSidebar();}
function updateUI(){if(!CU)return;var av=$('uAv');if(av){av.textContent=CU.ini||'?';av.style.background='linear-gradient(135deg,'+CU.color+','+CU.color+'80)';}if($('uName'))$('uName').textContent=CU.name;if($('uLvl'))$('uLvl').textContent=calcLvl(GS.totalPoints);}
// NAV
window.showMain=function(sec,btn){if(GS&&GS.qTimer){clearInterval(GS.qTimer);GS.qTimer=null;}hideAll();document.querySelectorAll('.ntab').forEach(function(t){t.classList.remove('on');});if(btn)btn.classList.add('on');if(sec==='levels'){showSec('sLevels');renderLevels();}else if(sec==='mini')showSec('sMini');};
window.goBack=function(){if(GS&&GS.qTimer){clearInterval(GS.qTimer);GS.qTimer=null;}if(asmSt.tid){clearInterval(asmSt.tid);asmSt.tid=null;}if(matSt.tid){clearInterval(matSt.tid);matSt.tid=null;}if(cblSt.tid){clearInterval(cblSt.tid);cblSt.tid=null;}$('modMini').classList.remove('on');hideAll();showSec('sLevels');document.querySelectorAll('.ntab').forEach(function(t,i){t.classList.toggle('on',i===0);});renderLevels();updateStats();};
// NIVELES
function renderLevels(){if(!GS)return;var cont=$('lvlCont');if(!cont)return;var subjs=SUBJECTS[GS.currentYear]||SUBJECTS.primero;cont.innerHTML=subjs.map(function(s){var keys=Object.keys(LEVELS).filter(function(k){return k.startsWith(s.id)&&LEVELS[k].year===GS.currentYear;});return '<div class="subj-sec"><div class="subj-hdr"><div class="subj-ic" style="color:'+s.color+'">'+s.icon+'</div><div><div class="subj-ti">'+s.name+'</div><div class="subj-de">'+s.desc+'</div></div></div><div class="lgrid">'+keys.map(function(k){return renderCard(k);}).join('')+'</div></div>';}).join('');}
function renderCard(k){
  var c=LEVELS[k],ul=GS.unlockedLevels.includes(k),done=GS.completedLevels.includes(k);
  var hasQ=QS[k]&&QS[k].length>0;
  var dc={Facil:'#10b981',Medio:'#f59e0b',Dificil:'#ef4444'}[c.title]||'#94a3b8';
  var cnt=done&&hasQ?QS[k].length:0;
  var btn;
  if(ul){
    btn='<button type="button" class="btn-play" data-lvl="'+k+'" onclick="startLevel(this.dataset.lvl)">Jugar &#9654;</button>';
  } else {
    btn='<button type="button" class="btn-play" data-lvl="'+k+'" onclick="unlockLvl(this.dataset.lvl)" '+(GS.totalPoints>=c.cost?'':'disabled')+'>Desbloquear ('+c.cost+'pts)</button>';
  }
  return '<div class="lcard '+(ul?'':'locked')+'">'
    +'<div class="lcard-top">'
    +'<div class="lcard-ic" style="color:'+c.color+'">'+c.icon+'</div>'
    +'<span class="diff" style="background:'+dc+'22;color:'+dc+'">'+c.title+'</span>'
    +'</div>'
    +'<h3>'+c.subj+' - '+c.title+'</h3>'
    +'<p>'+c.desc+'</p>'
    +'<div class="lcard-ft">'
    +'<span style="color:#64748b">'+cnt+'/'+(hasQ?QS[k].length:0)+' hechas</span>'
    +(ul?'<span class="ok-badge">&#10003;</span>':'<span class="lock-c">&#128274; '+c.cost+'pts</span>')
    +'</div>'
    +btn
    +'</div>';
}
window.chgYear=function(y,btn){if(!GS)return;GS.currentYear=y;document.querySelectorAll('.ytab').forEach(function(t){t.classList.remove('on');});if(btn)btn.classList.add('on');renderLevels();};
window.unlockLvl=function(k){if(!GS)return;var cost=LEVELS[k].cost;if(GS.totalPoints>=cost){GS.totalPoints-=cost;if(!GS.unlockedLevels.includes(k))GS.unlockedLevels.push(k);saveSess();updateStats();renderLevels();notify('Nivel desbloqueado! -'+cost+'pts','ok');}else notify('Necesitas '+cost+' puntos','er');};
// QUIZ
window.startLevel=function(k){if(!GS)return;if(!QS[k]||!QS[k].length){notify('Proximamente...','in');return;}GS.currentLevel=k;GS.cQs=shuffle([...QS[k]]);GS.cQ=0;GS.cCorr=0;GS.cTimes=[];showSec('sQuiz');$('compScr').classList.remove('on');document.querySelectorAll('.qtext-box,.brow,.trow').forEach(function(el){el.style.display='';});loadQ();};
function loadQ(){if(!GS||!GS.cQs||!GS.cQs.length)return;var q=GS.cQs[GS.cQ];if($('qCount'))$('qCount').textContent='Pregunta '+(GS.cQ+1)+'/'+GS.cQs.length;if($('qPts'))$('qPts').textContent=q.pts;if($('qTxt'))$('qTxt').textContent=q.q;var ai=$('aInp');if(ai){ai.value='';ai.disabled=false;setTimeout(function(){ai.focus();},50);}var fb=$('qFb');if(fb){fb.className='fb';fb.textContent='';}var bn=$('bNxt');if(bn)bn.classList.remove('on');startTimer();}
function startTimer(){if(GS.qTimer)clearInterval(GS.qTimer);var t=GS.timerSecs;updTimer(t);GS.qTimer=setInterval(function(){t--;updTimer(t);if(t<=0){clearInterval(GS.qTimer);GS.qTimer=null;timeUp();}},1000);}
function updTimer(t){var td=$('tNum'),tp=$('tProg');if(td){td.textContent=t;td.style.color=t<=10?'var(--err)':t<=15?'var(--warn)':'var(--c1)';}if(tp)tp.style.width=((t/GS.timerSecs)*100)+'%';}
function timeUp(){if(!GS||!GS.cQs||!GS.cQs.length)return;GS.cTimes.push(GS.timerSecs);var fb=$('qFb');if(fb){fb.textContent='Tiempo! Respuesta: '+GS.cQs[GS.cQ].a[0];fb.className='fb on to';}var ai=$('aInp');if(ai)ai.disabled=true;var bn=$('bNxt');if(bn)bn.classList.add('on');}
window.checkA=function(){if(!GS||!GS.cQs||!GS.cQs.length)return;if(GS.qTimer){clearInterval(GS.qTimer);GS.qTimer=null;}var td=$('tNum');var used=GS.timerSecs-parseInt(td?td.textContent:0);GS.cTimes.push(Math.max(0,used));var q=GS.cQs[GS.cQ];var ai=$('aInp');var ua=(ai?ai.value.trim():'').toLowerCase();function norm(s){return s.toLowerCase().replace(/^(el |la |los |las |un |una )/,'').normalize('NFD').replace(/[̀-ͯ]/g,'').replace(/\s+/g,' ').trim();}var ok=q.a.some(function(a){return norm(a)===norm(ua)||norm(ua).includes(norm(a));});var fb=$('qFb');if(fb){fb.textContent=ok?'Correcto! +'+q.pts+'pts ('+used+'s)':'Incorrecto. Respuesta: '+q.a[0];fb.className='fb on '+(ok?'ok':'er');}if(ok)GS.cCorr++;if(ai)ai.disabled=true;var bn=$('bNxt');if(bn)bn.classList.add('on');};
window.nextQ=function(){if(!GS)return;GS.cQ++;if(GS.cQ>=GS.cQs.length)finishQ();else loadQ();};
function finishQ(){if(!GS)return;if(GS.qTimer){clearInterval(GS.qTimer);GS.qTimer=null;}var total=GS.cQs.length,corr=GS.cCorr,pts=corr*(GS.cQs[0]?GS.cQs[0].pts:10);var avg=GS.cTimes.length?Math.round(GS.cTimes.reduce(function(a,b){return a+b;},0)/GS.cTimes.length):0;GS.totalPoints+=pts;GS.coins+=Math.floor(pts/5);if(!GS.completedLevels.includes(GS.currentLevel))GS.completedLevels.push(GS.currentLevel);if($('cCorr'))$('cCorr').textContent=corr+'/'+total;if($('cPts'))$('cPts').textContent=pts;if($('cAcc'))$('cAcc').textContent=Math.round((corr/total)*100)+'%';if($('cTime'))$('cTime').textContent=avg+'s';document.querySelectorAll('.qtext-box,.brow,.trow').forEach(function(el){el.style.display='none';});$('compScr').classList.add('on');updateStats();updateSidebar();saveSess();notify('Completado! +'+pts+'pts','ok');}
// ENSAMBLAJE
var asmSt={qs:[],idx:0,sc:0,co:0,corr:0,sel:null,tl:60,tid:null};
window.startAsm=function(){if(!GS)return;asmSt.qs=shuffle([...ASM_QS]).slice(0,5);asmSt.idx=0;asmSt.sc=0;asmSt.co=0;asmSt.corr=0;asmSt.sel=null;asmSt.tl=60;if(asmSt.tid)clearInterval(asmSt.tid);showSec('sAsm');loadAsmQ();asmSt.tid=setInterval(function(){asmSt.tl--;var el=$('asmTm');if(el){el.textContent=asmSt.tl;el.style.color=asmSt.tl<=10?'var(--err)':asmSt.tl<=30?'var(--warn)':'var(--c1)';}if(asmSt.tl<=0){clearInterval(asmSt.tid);endAsm();}},1000);};
function loadAsmQ(){var q=asmSt.qs[asmSt.idx];if(!q)return;if($('asmPg'))$('asmPg').style.width=(asmSt.idx/asmSt.qs.length*100)+'%';if($('asmQ'))$('asmQ').textContent=(asmSt.idx+1)+'/'+asmSt.qs.length;if($('asmSc'))$('asmSc').textContent=asmSt.sc;if($('asmCo'))$('asmCo').textContent=asmSt.co;if($('asmCat'))$('asmCat').textContent=q.cat;if($('asmHint'))$('asmHint').textContent=q.hint;if($('asmIc'))$('asmIc').innerHTML=q.icon;if($('asmTi'))$('asmTi').textContent=q.title;if($('asmDe'))$('asmDe').textContent=q.desc;asmSt.sel=null;var sub=$('asmSub');if(sub){sub.disabled=true;sub.style.display='';}var nxt=$('asmNxt');if(nxt)nxt.style.display='none';var fb=$('asmFb');if(fb){fb.className='afb';fb.textContent='';}var exp=$('expB');if(exp)exp.style.display='none';var opts=$('asmOpts');if(!opts)return;opts.innerHTML=q.opts.map(function(o,i){return '<div class="aopt" data-i="'+i+'" onclick="selAsm('+i+')"><div class="aopt-ic">'+o.ic+'</div><div>'+o.t+'</div></div>';}).join('');}
window.selAsm=function(i){if(asmSt.sel!==null)return;asmSt.sel=i;document.querySelectorAll('.aopt').forEach(function(el){el.classList.remove('sel');});var el=document.querySelector('.aopt[data-i="'+i+'"]');if(el)el.classList.add('sel');var sub=$('asmSub');if(sub)sub.disabled=false;};
window.subAsm=function(){if(asmSt.sel===null)return;var q=asmSt.qs[asmSt.idx];var ok=asmSt.sel===q.cor;document.querySelectorAll('.aopt').forEach(function(el){el.style.pointerEvents='none';el.classList.remove('sel');var i=parseInt(el.dataset.i);if(i===q.cor)el.classList.add('cor');else if(i===asmSt.sel&&!ok)el.classList.add('inc');});var fb=$('asmFb');if(fb){fb.textContent=ok?'Correcto! +'+q.pts+'pts':'Incorrecto. Era: '+q.opts[q.cor].t;fb.className='afb on '+(ok?'ok':'er');}if($('expTx'))$('expTx').textContent=q.exp;var exp=$('expB');if(exp)exp.style.display='block';if(ok){asmSt.sc+=q.pts;asmSt.co+=q.coins;asmSt.corr++;}var sub=$('asmSub');if(sub)sub.style.display='none';var nxt=$('asmNxt');if(nxt)nxt.style.display='block';if($('asmSc'))$('asmSc').textContent=asmSt.sc;if($('asmCo'))$('asmCo').textContent=asmSt.co;};
window.nxtAsm=function(){asmSt.idx++;if(asmSt.idx>=asmSt.qs.length)endAsm();else{loadAsmQ();var sub=$('asmSub');if(sub)sub.style.display='';}};
function endAsm(){if(asmSt.tid){clearInterval(asmSt.tid);asmSt.tid=null;}var bonus=Math.floor(asmSt.tl/4);asmSt.co+=bonus;if(asmSt.corr===asmSt.qs.length)asmSt.co+=25;GS.coins+=asmSt.co;if($('arCr'))$('arCr').textContent=asmSt.corr+'/'+asmSt.qs.length;if($('arSc'))$('arSc').textContent=asmSt.sc;if($('arCo'))$('arCo').textContent=asmSt.co+' monedas';if($('arAc'))$('arAc').textContent=Math.round((asmSt.corr/asmSt.qs.length)*100)+'%';showSec('sAsmRes');$('sAsmRes').style.display='block';updateStats();updateSidebar();saveSess();notify('Ensamblaje ok! +'+asmSt.co+' monedas','ok');}
// RELACIONAR
var matSt={pairs:[],selT:null,corr:0,sc:0,co:0,tl:90,tid:null,done:false};
window.startMatch=function(){if(!GS)return;var qs=shuffle([...MATCH_QS]);matSt.pairs=qs.map(function(q,i){return{tid:'t'+i,did:'d'+i,t:q.t,d:q.d,matched:false};});matSt.selT=null;matSt.corr=0;matSt.sc=0;matSt.co=0;matSt.tl=90;matSt.done=false;if(matSt.tid)clearInterval(matSt.tid);showSec('sMatch');renderMatGrid();if($('matPg'))$('matPg').style.width='0%';matSt.tid=setInterval(function(){matSt.tl--;var el=$('matTm');if(el)el.textContent=matSt.tl;if(matSt.tl<=0){clearInterval(matSt.tid);endMatch();}},1000);};
function renderMatGrid(){
  var grid=$('matGrid');if(!grid)return;
  var terms=shuffle(matSt.pairs.map(function(p){return{id:p.tid,text:p.t};}));
  var defs=shuffle(matSt.pairs.map(function(p){return{id:p.did,text:p.d};}));
  var th='<div class="mat-col"><h3>TERMINOS</h3>';
  terms.forEach(function(t){
    var d2=document.createElement('div');
    d2.className='mterm';d2.dataset.id=t.id;d2.textContent=t.text;
    d2.addEventListener('click',function(){selTerm(this.dataset.id);});
    th+=d2.outerHTML;
  });
  th+='</div>';
  var dh='<div class="mat-col"><h3>DEFINICIONES</h3>';
  defs.forEach(function(d){
    var d2=document.createElement('div');
    d2.className='mdef';d2.dataset.id=d.id;d2.textContent=d.text;
    d2.addEventListener('click',function(){selDef(this.dataset.id);});
    dh+=d2.outerHTML;
  });
  dh+='</div>';
  grid.innerHTML=th+dh;
  // Re-attach events after innerHTML
  grid.querySelectorAll('.mterm').forEach(function(el){el.addEventListener('click',function(){selTerm(this.dataset.id);});});
  grid.querySelectorAll('.mdef').forEach(function(el){el.addEventListener('click',function(){selDef(this.dataset.id);});});
  matSt.selT=null;
}
window.selTerm=function(id){if(matSt.done)return;document.querySelectorAll('.mterm.sel,.mdef.sel').forEach(function(el){el.classList.remove('sel');});if(matSt.selT===id){matSt.selT=null;return;}var el=document.querySelector('.mterm[data-id="'+id+'"]');if(el){el.classList.add('sel');matSt.selT=id;}};
window.selDef=function(id){if(matSt.done||!matSt.selT){if(!matSt.selT)notify('Selecciona un termino primero','in');return;}var tp=matSt.pairs.find(function(p){return p.tid===matSt.selT;}),dp=matSt.pairs.find(function(p){return p.did===id;});if(tp&&dp&&tp===dp){tp.matched=true;var te=document.querySelector('.mterm[data-id="'+tp.tid+'"]'),de=document.querySelector('.mdef[data-id="'+tp.did+'"]');if(te)te.classList.add('mat');if(de)de.classList.add('mat');matSt.corr++;matSt.sc+=20;matSt.co+=10;matSt.selT=null;notify('Correcto! +20pts','ok');if($('matPg'))$('matPg').style.width=(matSt.corr/matSt.pairs.length*100)+'%';if($('matCr'))$('matCr').textContent=matSt.corr+'/'+matSt.pairs.length;if($('matSc'))$('matSc').textContent=matSt.sc;if($('matCo'))$('matCo').textContent=matSt.co;if(matSt.corr===matSt.pairs.length)endMatch();}else{notify('Incorrecto','er');document.querySelectorAll('.mterm.sel,.mdef.sel').forEach(function(el){el.classList.remove('sel');});matSt.selT=null;}};
function endMatch(){if(matSt.done)return;matSt.done=true;if(matSt.tid){clearInterval(matSt.tid);matSt.tid=null;}var bonus=Math.floor(matSt.tl/10)+(matSt.corr===matSt.pairs.length?30:0);GS.coins+=matSt.co+bonus;GS.totalPoints+=matSt.sc;updateStats();updateSidebar();saveSess();notify('Relacionar ok! +'+(matSt.co+bonus)+' monedas','ok');goBack();}
// CABLEADO
var cblSt={idx:0,sc:0,co:0,tl:120,tid:null,drg:null,qs:[]};
window.startCable=function(){if(!GS)return;cblSt.idx=0;cblSt.sc=0;cblSt.co=0;cblSt.tl=120;cblSt.drg=null;cblSt.qs=shuffle([...CABLE_QS]);if(cblSt.tid)clearInterval(cblSt.tid);showSec('sCable');loadCbl();cblSt.tid=setInterval(function(){cblSt.tl--;var el=$('cbTm');if(el){el.textContent=cblSt.tl;el.style.color=cblSt.tl<=30?'var(--err)':cblSt.tl<=60?'var(--warn)':'var(--c1)';}if(cblSt.tl<=0){clearInterval(cblSt.tid);endCbl();}},1000);};
function loadCbl(){var q=cblSt.qs[cblSt.idx];if(!q)return;var cm={'verde-blanco':'#c8e6c9','verde':'#4caf50','naranja-blanco':'#ffe0b2','naranja':'#ff9800','azul-blanco':'#e3f2fd','azul':'#2196f3','marron-blanco':'#d7ccc8','marron':'#795548'};if($('cbQ'))$('cbQ').textContent=(cblSt.idx+1)+'/'+cblSt.qs.length;if($('cbSc'))$('cbSc').textContent=cblSt.sc;var shuffled=shuffle([...q.colors]);var cont=$('cbCont');if(!cont)return;cont.innerHTML='<div style="text-align:center;background:rgba(112,0,255,.07);border-radius:9px;padding:14px;margin-bottom:14px;border-left:4px solid var(--c2)"><h3 style="color:var(--c1);font-family:Orbitron,sans-serif;margin-bottom:5px">'+q.title+'</h3><p style="color:#e2e8f0;font-size:13px">'+q.desc+'</p><p style="color:#64748b;font-size:11px">'+q.exp+'</p></div><div class="cable-tools"><div><h4 style="text-align:center;color:var(--c1);font-family:Orbitron,sans-serif;margin-bottom:8px;font-size:12px">CABLES</h4><div class="cable-pal">'+shuffled.map(function(c){return'<div class="cable-item" draggable="true" data-c="'+c+'" data-orig="'+q.colors.indexOf(c)+'" style="background:'+(cm[c]||'#ccc')+'">'+c.replace('-','/')+'</div>';}).join('')+'</div></div><div><h4 style="text-align:center;color:var(--c1);font-family:Orbitron,sans-serif;margin-bottom:8px;font-size:12px">RJ45</h4><div class="rj45">'+[1,2,3,4,5,6,7,8].map(function(n){return'<div class="cslot" data-sl="'+(n-1)+'"><div class="snum">'+n+'</div></div>';}).join('')+'</div></div></div>';var nxt=$('cbNxt');if(nxt)nxt.style.display='none';cont.querySelectorAll('.cable-item').forEach(function(c){c.addEventListener('dragstart',function(e){cblSt.drg=e.target;e.dataTransfer.setData('text','x');});c.addEventListener('dragend',function(){cblSt.drg=null;});});cont.querySelectorAll('.cslot').forEach(function(s){s.addEventListener('dragover',function(e){e.preventDefault();s.classList.add('dragov');});s.addEventListener('dragleave',function(){s.classList.remove('dragov');});s.addEventListener('drop',function(e){e.preventDefault();s.classList.remove('dragov');if(!cblSt.drg)return;var ex=s.querySelector('.cable-item');if(ex){var pp=cblSt.drg.parentNode;s.removeChild(ex);pp.appendChild(ex);}s.appendChild(cblSt.drg);cblSt.drg=null;});});}
window.checkCbl=function(){var slots=document.querySelectorAll('.cslot');var order=[];var filled=true;slots.forEach(function(s){var c=s.querySelector('.cable-item');if(c)order.push(parseInt(c.dataset.orig));else filled=false;});if(!filled){notify('Coloca todos los cables','er');return;}var q=cblSt.qs[cblSt.idx];if(JSON.stringify(order)===JSON.stringify(q.correct)){var b=Math.floor(cblSt.tl/20);cblSt.sc+=20+b;notify('Correcto! +'+(20+b)+'pts','ok');setTimeout(function(){cblSt.idx++;if(cblSt.idx<cblSt.qs.length)loadCbl();else endCbl();},1200);}else notify('Orden incorrecto','er');};
window.nxtCbl=function(){cblSt.idx++;if(cblSt.idx<cblSt.qs.length)loadCbl();else endCbl();};
function endCbl(){if(cblSt.tid){clearInterval(cblSt.tid);cblSt.tid=null;}var co=Math.floor(cblSt.sc/6);GS.coins+=co;if($('crSc'))$('crSc').textContent=cblSt.sc;if($('crCo'))$('crCo').textContent=co+' monedas';if($('crTm'))$('crTm').textContent=cblSt.tl+'s';showSec('sCableRes');$('sCableRes').style.display='block';updateStats();updateSidebar();saveSess();notify('Cableado ok! +'+co+' monedas','ok');}
// AVATAR & SHOP
window.showAvatar=function(){if(!GS)return;hideAll();showSec('sAvatar');document.querySelectorAll('.ntab').forEach(function(t,i){t.classList.toggle('on',i===2);});['avBF','avHF'].forEach(function(id,i){var el=$(id);if(el)el.innerHTML=i===0?'&#129470;':'&#129302;';});[['avHatF','hat'],['avGlF','glasses'],['avItF','item']].forEach(function(pair){var el=$(pair[0]);var type=pair[1];if(el)el.innerHTML=GS.equippedItems[type]?(SHOP_ITEMS.find(function(s){return s.id===GS.equippedItems[type];})||{icon:''}).icon:'';});if($('avCS'))$('avCS').textContent=GS.coins;renderShop();};
function renderShop(){
  var g=$('shopG');if(!g||!GS)return;
  g.innerHTML='';
  SHOP_ITEMS.forEach(function(item){
    var owned=GS.ownedItems.includes(item.id);
    var equipped=GS.equippedItems[item.type]===item.id;
    var lbl=owned?(equipped?'Equipado':'Equipar'):(item.cost+' monedas');
    var div=document.createElement('div');
    div.className='sitem'+(owned?' owned':'');
    div.innerHTML='<div class="sitem-ic">'+item.icon+'</div><div class="sitem-nm">'+item.name+'</div><div class="sitem-co">'+lbl+'</div>';
    if(owned){
      div.style.cursor='pointer';
      div.addEventListener('click',(function(id,type){return function(){equipItem(id,type);};})(item.id,item.type));
    } else {
      var btn=document.createElement('button');
      btn.type='button';btn.textContent='Comprar';
      btn.style.cssText='margin-top:5px;padding:5px 10px;background:linear-gradient(135deg,var(--c2),#4c1d95);border:none;border-radius:7px;color:#fff;font-size:10px;cursor:pointer;width:100%';
      btn.addEventListener('click',(function(id){return function(){buyItem(id);};})(item.id));
      div.appendChild(btn);
    }
    g.appendChild(div);
  });
}
window.buyItem=function(id){if(!GS)return;var item=SHOP_ITEMS.find(function(i){return i.id===id;});if(!item)return;if(GS.coins>=item.cost){GS.coins-=item.cost;GS.ownedItems.push(id);saveSess();updateStats();renderShop();updateSidebar();notify('Compraste '+item.name,'ok');}else notify('Sin monedas','er');};
window.equipItem=function(id,type){if(!GS)return;GS.equippedItems[type]=GS.equippedItems[type]===id?null:id;updAvatar();renderShop();saveSess();if($('avCS'))$('avCS').textContent=GS.coins;};
function updAvatar(){if(!GS)return;var eq=GS.equippedItems;[['avHat','hat'],['avGl','glasses'],['avIt','item'],['avHatF','hat'],['avGlF','glasses'],['avItF','item']].forEach(function(pair){var el=$(pair[0]);if(el)el.innerHTML=eq[pair[1]]?(SHOP_ITEMS.find(function(i){return i.id===eq[pair[1]];})||{icon:''}).icon:'';});}
function updateSidebar(){if(!GS)return;if($('avLvl'))$('avLvl').textContent=calcLvl(GS.totalPoints);if($('avPts'))$('avPts').textContent=GS.totalPoints;if($('avCoins'))$('avCoins').textContent=GS.coins;if($('avProg'))$('avProg').textContent=Math.round((GS.completedLevels.length/36)*100)+'%';updAvatar();}
function updateStats(){if(!GS)return;if($('stPts'))$('stPts').textContent=GS.totalPoints;if($('stLvls'))$('stLvls').textContent=GS.completedLevels.length+'/36';if($('stCoins'))$('stCoins').textContent=GS.coins;updateUI();}
// DESAFIO EXTREMO
var modSt={idx:0,corr:0,sel:null,tl:60,tid:null,start:0,qs:[]};
window.startMinigame=function(){modSt.idx=0;modSt.corr=0;modSt.sel=null;modSt.tl=60;modSt.start=Date.now();modSt.qs=shuffle([...MINI_QS]).slice(0,5);if(modSt.tid)clearInterval(modSt.tid);$('modMini').classList.add('on');$('modCont').style.display='block';$('modRes').style.display='none';loadModQ();modSt.tid=setInterval(function(){modSt.tl--;var el=$('modTm');if(el)el.textContent=modSt.tl;if(modSt.tl<=0){clearInterval(modSt.tid);endMod();}},1000);};
function loadModQ(){var q=modSt.qs[modSt.idx];modSt.sel=null;if($('modQN'))$('modQN').textContent=modSt.idx+1;if($('modQTx'))$('modQTx').textContent=q.q;var opts=$('modOpts');if(opts)opts.innerHTML=q.opts.map(function(o,i){return'<div class="mgopt" onclick="selMod('+i+')">'+o+'</div>';}).join('');var s=$('modSub');if(s)s.disabled=false;}
window.selMod=function(i){if(modSt.sel!==null)return;modSt.sel=i;document.querySelectorAll('.mgopt').forEach(function(el){el.classList.remove('sel');});var el=document.querySelectorAll('.mgopt')[i];if(el)el.classList.add('sel');};
window.subMod=function(){if(modSt.sel===null)return;var q=modSt.qs[modSt.idx];var els=document.querySelectorAll('.mgopt');var s=$('modSub');if(s)s.disabled=true;if(modSt.sel===q.cor){if(els[modSt.sel])els[modSt.sel].classList.add('cor');modSt.corr++;}else{if(els[modSt.sel])els[modSt.sel].classList.add('inc');if(els[q.cor])els[q.cor].classList.add('cor');}setTimeout(function(){modSt.idx++;if(modSt.idx>=5)endMod();else loadModQ();},1200);};
function endMod(){if(modSt.tid){clearInterval(modSt.tid);modSt.tid=null;}var co=modSt.corr*5;var tm=Math.floor((Date.now()-modSt.start)/1000);if(GS)GS.coins+=co;$('modCont').style.display='none';$('modRes').style.display='block';if($('modCr'))$('modCr').textContent=modSt.corr+'/5';if($('modCo'))$('modCo').textContent=co+' monedas';if($('modTi'))$('modTi').textContent=tm+'s';var ti=$('modReTi');if(ti){ti.textContent=modSt.corr>=4?'Excelente!':modSt.corr>=3?'Bien!':'Sigue practicando';ti.style.color=modSt.corr>=4?'var(--ok)':modSt.corr>=3?'var(--warn)':'var(--err)';}updateStats();updateSidebar();saveSess();}
window.closeMod=function(){$('modMini').classList.remove('on');};
// CHATBOT
var cbOpen=false;
window.toggleCB=function(){cbOpen=!cbOpen;var w=$('cbWin'),b=$('cbBtn');if(cbOpen){w.classList.add('on');b.classList.add('open');$('cbInp').focus();}else{w.classList.remove('on');b.classList.remove('open');}};
function cbAdd(txt,usr){var c=$('cbMsgs');if(!c)return;var d=document.createElement('div');d.className='cb-msg '+(usr?'usr':'bot');var t=new Date().toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'});d.innerHTML='<div class="cb-bub">'+txt.replace(/\*\*(.*?)\*\*/g,'<strong style="color:var(--c1)">$1</strong>')+'<div class="cb-time">'+t+'</div></div>';c.appendChild(d);c.scrollTop=c.scrollHeight;}
function cbResp(msg){var m=msg.toLowerCase();var r=null;var kb=[{k:['hola','buenos'],r:'Hola! Soy NEXUS-AI. En que puedo ayudarte?'},{k:['jugar','como'],r:'Elige un nivel, responde preguntas escritas y gana puntos para desbloquear mas niveles.'},{k:['moneda','ganar'],r:'Gana monedas en minijuegos: Ensamblaje (hasta 60), Relacionar (hasta 50), Cableado (hasta 45).'},{k:['error','problema','soporte'],r:'Recarga la pagina (F5) o limpia la cache del navegador.'},{k:['avatar','tienda'],r:'Ve a Mi Avatar para comprar accesorios con monedas.'},{k:['gracias','adios'],r:'De nada! Buena suerte!'}];for(var i=0;i<kb.length;i++){if(kb[i].k.some(function(k){return m.includes(k);})){r=kb[i].r;break;}}if(!r)r='Prueba: como jugar, monedas, soporte.';var c=$('cbMsgs');var tp=document.createElement('div');tp.className='cb-msg bot';tp.innerHTML='<div class="typing"><span></span><span></span><span></span></div>';c.appendChild(tp);c.scrollTop=c.scrollHeight;setTimeout(function(){if(tp.parentNode)tp.remove();cbAdd(r,false);},600+Math.random()*500);}
window.cbSel=function(o){cbAdd(o,true);cbResp(o);};
window.cbSend=function(){var i=$('cbInp');if(!i||!i.value.trim())return;var m=i.value.trim();i.value='';cbAdd(m,true);cbResp(m);};
// ACCESIBILIDAD
var fsz=1,mxOn=true,mxIv=null;
window.toggleA11y=function(){var m=$('a11yMenu');if(m)m.style.display=m.style.display==='block'?'none':'block';};
window.toggleHC=function(){document.body.classList.toggle('hc');};
window.chgFont=function(d){fsz=Math.min(1.5,Math.max(0.8,fsz+d*0.1));document.body.style.fontSize=fsz+'rem';};
window.toggleDys=function(){var on=document.body.style.fontFamily.includes('Comic');document.body.style.fontFamily=on?'"Roboto",sans-serif':'"Comic Sans MS",Arial,sans-serif';};
window.toggleMx=function(){mxOn=!mxOn;if(mxOn)startMx();else stopMx();};
function startMx(){var bg=$('mxBg');if(!bg)return;if(mxIv)clearInterval(mxIv);function drop(){if(!mxOn)return;var el=document.createElement('div');el.className='mx-drop';el.style.left=Math.random()*100+'vw';el.style.animationDuration=(2+Math.random()*2)+'s';bg.appendChild(el);setTimeout(function(){el.remove();},5000);}for(var i=0;i<15;i++)setTimeout(drop,i*200);mxIv=setInterval(function(){if(mxOn)drop();},250);}
function stopMx(){mxOn=false;if(mxIv){clearInterval(mxIv);mxIv=null;}var bg=$('mxBg');if(bg)bg.querySelectorAll('.mx-drop').forEach(function(el){el.remove();});}
// INIT - usando window.onload para esperar todo
window.onload=function(){
  try{startMx();}catch(e){}
  var ai=$('aInp');
  if(ai)ai.addEventListener('keydown',function(e){if(e.key==='Enter'&&!ai.disabled)checkA();});
  var ok=false;
  try{ok=loadSess();}catch(e){console.warn('Session error:',e);}
  if(ok){
    try{startGame(CU);}catch(e){console.error('startGame error:',e);ok=false;}
  }
  if(!ok){
    var l=$('login');
    if(l&&l.classList.contains('gone'))l.classList.remove('gone');
  }
};

